---
- name: Deploy and start Apache HTTPD service
  hosts: lamp
  vars:
    firewall: firewalld
    rule: 80

  tasks:
    - name: Required packages are installed and up to date
      yum:
        name:
          - "{{ firewall }}"
        state: latest

    - name: The {{ firewall }} service is started and enabled
      service:
        name: "{{ firewall }}"
        enabled: true
        state: started

    - name: Web content is in place
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html

    - name: The firewall port for {{ rule }} is open
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

- name: Verify the Apache service
  hosts: localhost
  become: false

  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: "http://{{ ansible_fqdn }}"
        status_code: 200
